### ISSUE TITLE
Odd license statement in Odd

### ISSUE THREAD

**Issue by donaldr3** [stealth/odd#1]
Just an FYI, the GPL allows any use of the software, including in a commercial setting or for sale. The license itself grants them permission to do so. Trying to prevent such use would be a further restriction, which users are free to ignore. So you may not be accomplishing what you expect with your licensing header. Having proper headers is always a good idea, so please check out this guide on how to use the GPL on your programs https://www.gnu.org/licenses/gpl-howto.html. Thanks.

**Comment by stealth** [comment]
switched to GPL3
